apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: QWxp  # Base64 for "Ali"
  POSTGRES_PASSWORD: MTIzMjEy  # Base64 for "123212"
  POSTGRES_DB: Zmxhc2tfd2ViYXBw  # Base64 for "flask_webapp"